//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecjalnyTyper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.Vote = new HashSet<Vote>();
        }
    
        public int Id { get; set; }
        public string Team1 { get; set; }
        public string Team2 { get; set; }
        public Nullable<int> Team1_Score { get; set; }
        public Nullable<int> Team2_Score { get; set; }
        public int Score { get; set; }
        public int Set_Id { get; set; }
        public Nullable<bool> Completed { get; set; }
        public System.DateTime Match_start_date { get; set; }
    
        public virtual Set Set { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vote> Vote { get; set; }
    }
}
